### ISSUE TITLE
CSSRule and group properties

### ISSUE THREAD

**Issue by chexov** [st-js/steel#2]
I wonder if you already solved this style of CSS rues in your local commits:

```
.magic-background{
            background: #3b3d3f;
            background: linear-gradient(#3b3d3f, #1e1e1f);
            background: -webkit-linear-gradient(#3b3d3f, #1e1e1f);
            background: -o-linear-gradient(#3b3d3f, #1e1e1f);
            background: -moz-linear-gradient(#3b3d3f, #1e1e1f);
}
```

**Comment by acraciun** [comment]
The goal of this part was to strong-type the CSS also - as they tend to become quite big over time and very hard to control. Another point was to allow components to propose some kind of "CSS API" to allow external users to style only some specific part.
The part you're asking about is not done yet, but could be part of the actual renderer of these rules depending on the browser. What's important to understand is that the rules are kept as generate JS (not CSS) and the CSS rules are created at runtime. That's why you'll not even need to specify all these rule as the browser-specific renderer will know what rule to create.
